[package]
name = "tls-websockets-example"
version = "0.1.0"
authors = ["SauceChord"]
edition = "2018"

[dependencies]
tungstenite = { version = "0.14.0", features = ["rustls-tls"] }
rustls = { version = "0.19.1" }
env_logger = { version = "0.9.0" }